Repository schramm-famm/me-you, pull requests merged in 2020-04, with the labels that each got.

#29 Create `Login`/`Register` view
  babel.config.js
  package-lock.json
  package.json
  public/favicon.ico
  public/img/icons/android-chrome-192x192.png
  public/img/icons/android-chrome-512x512.png
  public/img/icons/android-chrome-maskable-192x192.png
  public/img/icons/android-chrome-maskable-512x512.png
  public/img/icons/apple-touch-icon-120x120.png
  public/img/icons/apple-touch-icon-152x152.png
  public/img/icons/apple-touch-icon-180x180.png
  public/img/icons/apple-touch-icon-60x60.png
  public/img/icons/apple-touch-icon-76x76.png
  public/img/icons/apple-touch-icon.png
  public/img/icons/favicon-16x16.png
  public/img/icons/favicon-32x32.png
  public/img/icons/msapplication-icon-144x144.png
  public/img/icons/mstile-150x150.png
  public/index.html
  public/stylesheets/riht.css
  src/assets/logo.png
  src/components/ConversationList.vue
  src/components/Login.vue
  src/components/Register.vue
  src/components/conversation/Conversation.vue
  src/components/conversation/handlers.js
  src/router/index.js
  src/services/index.js
  src/services/user.js
  src/store/alert.js
  src/store/index.js
  src/store/user.js
  src/utils.js
  src/views/Conversations.vue
  src/views/LandingPage.vue
Labels: enhancement

#31 Integrate backend APIs into conversation-related functionality
  .eslintrc.js
  package-lock.json
  package.json
  public/stylesheets/riht.css
  src/assets/add-24px.svg
  src/assets/more_vert-24px.svg
  src/components/Conversation.vue
  src/components/ConversationItem.vue
  src/components/ConversationList.vue
  src/components/ConversationsHome.vue
  src/components/Login.vue
  src/components/MoreMenu.vue
  src/components/Register.vue
  src/components/conversation/constants.js
  src/components/conversation/dom.js
  src/components/conversation/handlers.js
  src/components/conversation/protocol.js
  src/router/index.js
  src/services/conversations.js
  src/services/conversationsMock.js
  src/services/index.js
  src/services/models/ack.js
  src/services/models/activeUser.js
  src/services/models/caret.js
  src/services/models/checkpoint.js
  src/services/models/delta.js
  src/services/models/domElement.js
  src/services/models/index.js
  src/services/models/init.js
  src/services/models/sync.js
  src/services/models/update.js
  src/services/models/userJoin.js
  src/services/models/userLeave.js
  src/services/models/wsexception.js
  src/services/models/wsmessage.js
  src/services/user.js
  src/services/userMock.js
  src/services/utils.js
  src/services/websocket.js
  src/store/conversations.js
  src/store/index.js
  src/store/user.js
  src/utils.js
  src/views/Conversations.vue
  vue.config.js
Labels: enhancement

#34 Add UI popup for creating conversations
  src/components/ConversationList.vue
  src/components/CreateConversationMenu.vue
  src/services/conversations.js
  src/store/conversations.js
Labels: enhancement

#35 Add UI popup for adding conversation members
  public/stylesheets/riht.css
  src/assets/person_add-24px.svg
  src/components/AddUserMenu.vue
  src/components/Conversation.vue
  src/components/ConversationList.vue
  src/components/CreateConversationMenu.vue
  src/components/Login.vue
  src/components/MoreMenu.vue
  src/components/Register.vue
  src/services/user.js
  src/services/utils.js
  src/store/alert.js
  src/store/conversations.js
  src/store/user.js
Labels: enhancement

#40 Implement various fixes
  src/components/Conversation.vue
  src/components/ConversationList.vue
  src/services/models/update.js
  src/services/models/wsmessage.js
  src/store/conversations.js
Labels: bug

#44 Handle new lines properly
  src/services/models/domElement.js
  src/store/conversations.js
Labels: bug

#45 Redirect client to `/conversations` on error
  public/stylesheets/riht.css
  src/components/Conversation.vue
  src/components/ConversationsHome.vue
  src/store/conversations.js
Labels: bug, enhancement

#48 More fixes
  public/stylesheets/riht.css
  src/components/AddUserMenu.vue
  src/components/Conversation.vue
  src/components/ConversationList.vue
  src/services/models/domElement.js
  src/services/models/update.js
  src/store/conversations.js
Labels: bug
